# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 399eeca8c9ae94de27ada1ce9d1a9fca10a3a926e72cc24086007c7b3467ccd6ccd809b3e85033cd5d9b47a70e41330ecb350f26f1aef880df877275a61e236e

test:
  secret_key_base: 4f83593eab6bca3157ad18ccd99c5ce8562ff78ddf5902f85a5f19ea7e6733383b3c18cba31a79d760b989dce4e1dd50a35ea9fd79e59ca046019105c832958b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
